// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kalougata/bandhub/internal/common"
	"github.com/kalougata/bandhub/internal/server"
)

// Injectors from wire.go:

func NewApp() (*common.Server, func(), error) {
	engine := server.NewServerHTTP()
	commonServer := common.NewServer(engine)
	return commonServer, func() {
	}, nil
}
