// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kalougata/bandhub/api/v1"
	"github.com/kalougata/bandhub/internal/common"
	"github.com/kalougata/bandhub/internal/controller"
	"github.com/kalougata/bandhub/internal/server"
)

// Injectors from wire.go:

func NewApp() (*common.Server, func(), error) {
	userController := controller.NewUserController()
	apiRouter := v1.NewAPIRouter(userController)
	engine := server.NewServerHTTP(apiRouter)
	commonServer := common.NewServer(engine)
	return commonServer, func() {
	}, nil
}
